config/routes.rb
Rails.application.routes.draw do
  resources :order_items, xhr: true

  get 'cart', to: 'cart#show'
  resources :product_categories
  get 'menu', to: 'menu#index'
  get 'search', to: 'menu#search'
  resources :products
  root 'pages#home'
  get 'catering', to: 'pages#catering'
  get 'info', to: 'pages#info'


  #get 'cert_categories#index'
  #get 'help', to: 'static_pages#help'
  #get 'about', to: 'static_pages#about'
  resources :articles

  get 'articles_1', to: 'articles#index1'
  get 'signup', to: 'users#new'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories 
end

app/models/cert_category.rb
class CertCategory < ApplicationRecord
  has_many :cert_join_categories
  has_many :certificates, through: :cert_join_categories
end

app/models/cert_join_category.rb
class CertJoinCategory < ApplicationRecord
  belongs_to :certificate
  belongs_to :cert_category
end

app/models/certificate.rb
class Certificate < ApplicationRecord

  validates :title, presence: true

  has_many :cert_join_categories
  has_many :cert_categories, through: :cert_join_categories
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    return unit_price * quantity
  end


  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_one_attached :image
  has_many :order_items 
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password

  


end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items 
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats

  def index
    @page = 'menu'
    @products = Product.all
    @order_item = current_order.order_items.new 
  end

  def search
    query = params[:search]

    results = Product.where('name LIKE ?', "%#{query}%")
    if params[:filter] == 'Select Filter'
      @products = results
    else
      # 'Dairy Free' -> 'Dairy_Free' -> 'dairy_free' -> :dairy_free
      symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym
      # @products = results.where(:dairy_free => true)
      @products = results.where(symbol => true)
    end
  end

  private

  def set_cats
    @cats = ProductCategory.all.where(display: true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page = 'home'
  end

  def catering
    @page = 'catering'
  end

  def info
    @page = 'info'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit

  end

  def update

    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    # Use Find by id to avoid potential erros
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of $#{current_order.subtotal}", cart_path %>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
<h3><%= item.product.name%></h3>
<h3><%= item.product.price %></h3>
<%= form_with model: item do |f|%>
<%= f.hidden_field :product_id, value: item.product.id %>
<%= f.number_field :quantity, value: item.quantity.to_i%>
<%= f.submit "Update Cart" %>
<%= link_to "Remove Items", item, method: :delete, remote: true %>
<% end%>
<h2>Subtotal: <%= item.total %></h2>
<% end %>

<h3>Your current order has a total of: <%= current_order.subtotal %></h3>

app/views/cart/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>
<div id="cart-item">
    <%= render 'cart_items'%>
</div>

<hr>

app/views/menu/_products.html.erb
<div class="row">
    <% @cats.each do |cat| %>
    <% if cat.products.where(featured: true).first.image.attached? %>
    <%= image_tag(cat.products.where(featured: true).first.image, class:'img-fluid')%>
    <% end %>
    <div class="col-12">
        <h1 style="text-align:center;"><%= cat.heading %></h1>
        <hr />
    </div>
    <% @products.each do |product| %>
    <% if product.product_category == cat %>
    <div class="col-4">
        <h5>
            <%= product.name %>
        </h5>
        <p>
            <%= product.description%>
        </p>
        <span><%= product.price %> <%= "| Available for catering" if product.catering %></span>
        <%= form_with model: @order_item do |f| %>
        <%= f.hidden_field :product_id, value: product.id %>
        <%= f.number_field :quantity, value: 1, min: 1 %>
        <%= f.submit "Add To Cart" %>
        <% end %>
    </div>
    <% end %>
    <% end %>
    <% end %>
</div>

app/views/menu/index.html.erb
<div class="menu-container">
    <div class="row">
        <div class="col-12">
            <%= form_tag(search_path, method: "get", remote: true) do %>
            <div class="input-group mb-5">
                <div class="col-8" style="padding:0">
                    <%= text_field_tag :search, '', class:'form-control', placeholder: 'Search...', onkeydown:'clickSubmit();'%>
                </div>
                <div class="col-4" style="padding:0">
                    <%= select_tag "filter", options_for_select(['Select Filter',
                    'Dairy Free',
                    'Gluten Free',
                    ]), class:'custom-select', onchange:'clickSubmit()'%>
                    <%= submit_tag "Search", class:'btn btn-dark', id:'search_submit', style:'display:none'%>
                </div>
            </div>
            <% end %>
        </div>
    </div>
    <div id="menu-products-container">
        <%= render 'menu/products'%>
    </div>
</div>

<script>
    function clickSubmit() {
        $("#search_submit").trigger("click");
    }
</script>

app/views/menu/search.js.erb
$("#menu-products-container").html("<%= j render 'menu/products' %>");

app/views/users/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-none rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
          <%= f.text_field :username, class: "form-control shadow rounder", placeholder: "username"%>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, rows: 10, class: "form-control shadow rounded", placeholder: "Email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "Password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
      <div class="flickr_pagination">
        <%= will_paginate @users, :container => false %>
      </div>
  <div class="container">

      <% @users.each do |user| %>
          <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>

                  <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>

                  <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete,
                  data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>

          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class = "text-center mt-4"> Sign up for CCConnect Blog </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>


  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>



<h3 class="text-center mt-4">Articles</h3>
    <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>

      <%= render 'articles/article' %>

    <div class="flickr_pagination mb-4">
      <%= will_paginate @articles, :container => false %>
    </div>