config/routes.rb
Rails.application.routes.draw do
  resources :order_items, xhr: true

  get 'cart', to: 'cart#show'
  resources :product_categories
  get 'menu', to: 'menu#index'
  get 'search', to: 'menu#search'
  resources :products
  root 'pages#home'
  get 'catering', to: 'pages#catering'
  get 'info', to: 'pages#info'


  #get 'cert_categories#index'
  #get 'help', to: 'static_pages#help'
  #get 'about', to: 'static_pages#about'
  resources :articles

  get 'articles_1', to: 'articles#index1'
  get 'signup', to: 'users#new'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories 
end

app/models/cert_category.rb
class CertCategory < ApplicationRecord
  has_many :cert_join_categories
  has_many :certificates, through: :cert_join_categories
end

app/models/cert_join_category.rb
class CertJoinCategory < ApplicationRecord
  belongs_to :certificate
  belongs_to :cert_category
end

app/models/certificate.rb
class Certificate < ApplicationRecord

  validates :title, presence: true

  has_many :cert_join_categories
  has_many :cert_categories, through: :cert_join_categories
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    return unit_price * quantity
  end


  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_one_attached :image
  has_many :order_items 
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
  has_secure_password

  


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]





  def show

  end

  def index

    @articles = Article.paginate(page: params[:page], per_page: 5)

  end

  def index1
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true)
  end

  def new
    @article = Article.new

  end

  def edit

  end

  def create
    @article = Article.new(article_params)

    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end


  def update

    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
 end

 private

 def set_article
   @article = Article.find(params[:id])

 end

 def article_params
   params.require(:article).permit(:title, :description, category_ids: [])
 end

 def require_same_user
   if current_user != @article.user && !current_user.admin?
     flash[:alert] = "You can only edit or delete your own article"
     redirect_to @article
  end
end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items 
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats

  def index
    @page = 'menu'
    @products = Product.all
    @order_item = current_order.order_items.new 
  end

  def search
    query = params[:search]

    results = Product.where('name LIKE ?', "%#{query}%")
    if params[:filter] == 'Select Filter'
      @products = results
    else
      # 'Dairy Free' -> 'Dairy_Free' -> 'dairy_free' -> :dairy_free
      symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym
      # @products = results.where(:dairy_free => true)
      @products = results.where(symbol => true)
    end
  end

  private

  def set_cats
    @cats = ProductCategory.all.where(display: true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @page = 'home'
  end

  def catering
    @page = 'catering'
  end

  def info
    @page = 'info'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    # Use Find by id to avoid potential erros
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
            <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <% if article.categories.any? %>
            <div class="mt-2"><%= render article.categories %></div>
            <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
          <% if logged_in? && (article.user == current_user || current_user.admin? ) %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(article.created_at) %> ago,
          edited <%= time_ago_in_words(article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-none rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounder", placeholder: "Title of article"%>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

      <div class="form-group row">
        <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
          <%= f.collection_select(:category_ids, Category.all, :id, :name,
          { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true}) %>

          </div>
      </div>


        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
  </div>
</div>

app/views/articles/_search_form.html.erb
<%= search_form_for @q do |f| %>
    <%= f.search_field :title_or_description_cont, placeholder: "Search..." %>
    <%= f.submit "Search!" %>
<% end %>

app/views/articles/edit.html.erb
<div id = "page-content">
<h1 class = "text-center mt-4"> Update article </h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

</div>

app/views/articles/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">All Articles</h1>

  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= render 'article' %>

  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/articles/index1.html.erb
<p id="notice"><%= notice %></p>

<div class = "container">
<h1>Articles</h1>

<%= render 'articles/search_form.html.erb' %>
<table class = "table">
  <thead>
    <tr>
      <th><%= sort_link(@q, :title, "Title", default_order: :asc) %></th>
      <th><%= sort_link(@q, :description, "Article Content", default_order: :desc) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

</div>

app/views/articles/new.html.erb
<div id = "page-content">
  <h1 class = "text-center mt-4"> Create new article </h1>

  <%= render 'form' %>

  <%= link_to 'Return to articles listing', articles_path %>

</div>

app/views/articles/show.html.erb
<div id="page-content">
  <h2 class="text-center mt-4"><%= @article.title %></h2>

  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <%= render @article.categories %> 
          <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin? ) %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>